const words = [
  "apple", "banana", "chair", "dog", "elephant", "flower",
  "guitar", "house", "ice cream", "jacket", "key", "lion", "moon", "notebook", "orange", "piano", "queen",
  "rabbit", "sun", "table", "umbrella", "violin", "watermelon", "xylophone", "yellow", "zebra", "airplane", "book", "clock",
  "door", "egg", "fire", "grass", "hat", "ink", "jelly", "kite", "lamp", "mountain", "necklace", "ocean", "pizza", "rainbow", "shoe",
  "tree", "unicorn", "volleyball", "opaque", "vague", "waterfall", "cup", "water", "plant", "ball", "car", "boat", "bus", "duck", "cat",
  "pig", "bird", "turtle", "fish", "frog", "bee", "butterfly", "ant", "ladybug", "spider", "worm", "snail", "bunny", "bear", "fox", "monkey", "tiger",
  "giraffe", "crocodile", "penguin", "parrot", "owl", "seagull", "crab", "shark", "dolphin", "whale", "sunflower", "daisy",
  "rose", "tulip", "buttercup", "dandelion", "corn", "carrot", "tomato", "potato", "pumpkin", "apple",
  "grapes", "watermelon", "orange", "peach", "strawberry", "blueberry", "raspberry", "blackberry", "kiwi", "spoon", "fork", "knife", "plate", "cupcake", 
  "donut", "cookie", "candy", "popcorn",
  "juice", "milk", "chocolate", "peanut", "butter", "jellyfish", "dragonfly", "grasshopper", "mosquito", "cricket", "paint", "brush", "crayon", "marker", 
  "pencil", "eraser", "ruler", "scissors", "glue", "tape",
   "screwdriver", "nail", "screw", "nut", "sock", "shoe", "pants", "shirt", "dress", "skirt", "sweater", "hoodie", "jacket",
  "hat", "cap", "gloves", "scarf", "tie", "belt", "backpack", "purse", "wallet", "money", "phone", "computer", "tablet", "television", "camera", "keyboard",
   "mouse", "speaker", "microphone",
  "carrot", "celery", "onion", "garlic", "cabbage", "lettuce", "spinach", "broccoli", "cauliflower", "pepper", "corn", "peas", "beans", "rice", "noodle", 
  "bread", "butter", "jam",
];
  export { words };